# Generated by Django 3.2.23 on 2023-11-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [  #список миграций, которые нужно провести перед этой
    ]

    operations = [   #описание все изменений, которые нужно провести в бд
        migrations.CreateModel( #надо добавить поле CreateModel к модели SortedAray
            name='SortedArray',
            fields=[ #с названиеями такими то
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array_name', models.CharField(max_length=100)),
                ('sorted_array', models.TextField()),
            ],
        ),
    ]
